import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["supabase/functions/**/*.{ts,tsx}", "src/pages/admin/**/*.{ts,tsx}"],
    rules: {
      // Edge functions and the legacy internal admin use provider payloads whose
      // shapes are validated at their trust boundaries rather than by ESLint.
      "@typescript-eslint/no-explicit-any": "off",
      "no-useless-escape": "off",
    },
  },
  {
    files: ["supabase/functions/mcp/index.ts"],
    rules: {
      // This bundle is generated by @lovable.dev/mcp-js and is overwritten
      // during builds; its emitted `var` declarations are not authored code.
      "no-var": "off",
    },
  },
);
