import { useLanguage } from '@/i18n/LanguageContext';
import { SectionContainer } from '@/components/SectionContainer';
import { ScrollReveal, StaggerContainer, StaggerItem } from '@/components/motion/ScrollReveal';
import { Compass, Layers, GitBranch, ShieldCheck } from 'lucide-react';

/**
 * SocialProofSection — Methodology cards.
 *
 * IMPORTANT (mem://constraints/no-fake-proof):
 * This section MUST NOT contain invented testimonials, fake client logos,
 * or unverified performance metrics. When real, verifiable proof becomes
 * available, gate it behind siteConfig.trustBrandsEnabled / proofNumbersEnabled.
 *
 * Until then, we show our methodology — what we actually do — instead of
 * fabricated social proof.
 */
export function SocialProofSection() {
  const { isEnglish } = useLanguage();

  const pillars = isEnglish
    ? [
        {
          icon: Compass,
          title: 'Evidence over opinion',
          description:
            'Every recommendation is grounded in measured signals from your site — PageSpeed, security headers, structured data, content evidence. No hunches.',
        },
        {
          icon: Layers,
          title: 'Deterministic scoring',
          description:
            'Your maturity score is computed from weighted, transparent rules — not generated by an AI. AI only translates results into business language.',
        },
        {
          icon: GitBranch,
          title: 'Build, measure, iterate',
          description:
            'We deploy in tight loops with telemetry from day one. You see what moves the needle and what doesn\'t — no black box.',
        },
        {
          icon: ShieldCheck,
          title: 'Swiss data discipline',
          description:
            'Consent-first analytics, GDPR/FADP aligned, no dark patterns. Your visitors\' trust is part of the asset we build.',
        },
      ]
    : [
        {
          icon: Compass,
          title: 'Evidenz statt Bauchgefühl',
          description:
            'Jede Empfehlung basiert auf gemessenen Signalen deiner Seite — PageSpeed, Security-Header, strukturierte Daten, Content-Evidenz. Keine Vermutungen.',
        },
        {
          icon: Layers,
          title: 'Deterministisches Scoring',
          description:
            'Dein Reifegrad wird aus gewichteten, transparenten Regeln berechnet — nicht von einer KI erfunden. KI übersetzt Resultate nur in Business-Sprache.',
        },
        {
          icon: GitBranch,
          title: 'Bauen, messen, iterieren',
          description:
            'Wir liefern in engen Schleifen mit Telemetrie ab Tag eins. Du siehst, was wirkt und was nicht — keine Black Box.',
        },
        {
          icon: ShieldCheck,
          title: 'Schweizer Daten-Disziplin',
          description:
            'Consent-first Analytics, DSGVO/DSG-konform, keine Dark Patterns. Das Vertrauen deiner Besucher ist Teil des Assets, das wir bauen.',
        },
      ];

  return (
    <SectionContainer background="muted" className="relative overflow-hidden">
      <div className="absolute inset-0 gradient-mesh opacity-30" />

      <div className="relative">
        <ScrollReveal>
          <div className="text-center mb-12 max-w-2xl mx-auto">
            <p className="text-xs font-semibold tracking-[0.2em] text-muted-foreground uppercase mb-3">
              {isEnglish ? 'How we work' : 'Wie wir arbeiten'}
            </p>
            <h2 className="font-display mb-4">
              {isEnglish
                ? 'Method, not marketing claims.'
                : 'Methode, nicht Marketing-Versprechen.'}
            </h2>
            <p className="text-muted-foreground text-lg">
              {isEnglish
                ? 'We don\'t parade testimonials. We show you the rules of engagement — so you can judge fit before you commit.'
                : 'Wir paradieren keine Testimonials. Wir zeigen die Spielregeln — damit du den Fit beurteilen kannst, bevor du dich bindest.'}
            </p>
          </div>
        </ScrollReveal>

        <StaggerContainer
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
          staggerDelay={0.1}
        >
          {pillars.map((pillar, index) => {
            const Icon = pillar.icon;
            return (
              <StaggerItem key={index}>
                <div className="h-full p-6 rounded-2xl bg-card/60 backdrop-blur-sm border border-border/50 hover:border-primary/30 transition-all duration-300">
                  <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                    <Icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-semibold text-lg mb-2 leading-tight">
                    {pillar.title}
                  </h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {pillar.description}
                  </p>
                </div>
              </StaggerItem>
            );
          })}
        </StaggerContainer>
      </div>
    </SectionContainer>
  );
}
