// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL ?? "";
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? "";
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads submitted through the site (newest first). Requires admin role.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of leads to return."),
    status: z.string().optional().describe("Optional status filter, e.g. 'new', 'contacted'."),
    lead_type: z.string().optional().describe("Optional lead type filter, e.g. 'audit', 'call'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, lead_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("leads").select("id, created_at, name, email, phone, lead_type, status, industry, service_area, pre_score_bucket, pre_score_total, language").order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (lead_type) query = query.eq("lead_type", lead_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead detail",
  description: "Fetch full details for a single lead by id. Requires admin role.",
  inputSchema: { id: z2.string().uuid().describe("The lead UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("leads").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-calls.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_calls_default = defineTool3({
  name: "list_calls",
  title: "List voice calls",
  description: "List recent voice agent calls with outcome and language. Requires admin role.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Maximum number of calls to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("calls").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { calls: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-analysis-reports.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_analysis_reports_default = defineTool4({
  name: "list_analysis_reports",
  title: "List canonical audits",
  description: "List recent canonical website audit states. Requires admin role.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(20).describe("Maximum number of reports.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("audit_requests").select("id, normalized_domain, company_name, language, audit_type, status, overall_score, score_version, report_viewed_at, cta_clicked_at, email_sent_at, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { audits: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/add-do-not-call.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var add_do_not_call_default = defineTool5({
  name: "add_do_not_call",
  title: "Add phone to do-not-call list",
  description: "Add a phone number to the do-not-call list so the voice agent will no longer contact it. Requires admin role.",
  inputSchema: {
    phone: z5.string().min(5).describe("Phone number in E.164-ish format, e.g. +41791234567."),
    reason: z5.string().optional().describe("Optional reason note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ phone, reason }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("do_not_call").insert({ phone, reason: reason ?? null }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${phone} to do-not-call list.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "akxdeuvxvhecvddxyqnd";
var mcp_default = defineMcp({
  name: "itsfeierabend-mcp",
  title: "itsFeierabend.ch",
  version: "0.1.0",
  instructions: "Tools to inspect leads, voice calls, and website analysis reports for itsFeierabend.ch, plus adding numbers to the do-not-call list. All tools act as the signed-in admin user; row-level security enforces access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, list_calls_default, list_analysis_reports_default, add_do_not_call_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
